### ISSUE TITLE
Make @VorlonCD a contributor

### ISSUE THREAD

**Issue by doudar** [gentlepumpkin/bi-aidetection#51]
It seems the community as a whole is having a lot of issues that have been fixed in the @VorlonCD fork. He has pushed a lot of commits that haven't been merged into the main. 

As I can greatly appreciate not having the time to work on side projects, any chance you would consider making @VorlonCD a contributor (at least temporarily) so that he can merge his many wonderful commits into your awesome base so there is less confusion and more successful adoption of your great work?

**Comment by Wumfie** [comment]
Yes. Or at least link his project on the forum page / this page.

**Comment by Lazersfly** [comment]
I just added a link to VorlonCD's fork on the README, Gentlepumpkin should be linking it in the forum post later today. Some of VorlonCD's commits have been merged to the dev branch, but for now we think it is best for the community to focus on VorlonCD's fork.
