### ISSUE TITLE
Enable RETAIN flag MQTT

### ISSUE THREAD

**Issue by YOZZOPANOZZO** [gentlepumpkin/bi-aidetection#64]
I'm currently using this tool  alongside home Hassitant. With the latest home hassitant update MQTT binary sensors now require a RETAIN flag, otherwise their state will be set to unknown . Is the flag currently supported?

**Comment by VorlonCD** [comment]
Over in my fork of @gentlepumpkin 's project, you have a lot more control over a lot of things and with MQTT you can set retain:

https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

It should use/migrate your existing settings if you install to the same folder, but just make a backup first to be sure.

**Comment by YOZZOPANOZZO** [comment]
Thanks, my config was imported successfully, unfortunately for some reason the mqtt action is run only if I manually press test, but not when there is a detection. Any idea why? Telegram actions run fine.

EDIT: It seems that that when testing mqtt the correct payload is sent, but when a dectection occurs the confidence percentange is also in the payload, any idea how to remove it?
![Screenshot 2022-02-06 005633](https://user-images.githubusercontent.com/54823311/152663008-8b50d71b-b18e-4547-ae93-e29fc7687387.png)

EDIT 2 :  Fixed, just had to change the detection format to [Label] in the actions menu.
